### PR TITLE
latest Update README.md

### PR DESCRIPTION
**Pull request by cryptonit**
some additional explaination some command typo fixes

### CODE REVIEW

**Comment by PeterTheOne** [comment]
nice. please also replace `u` with `you` and `ur` with `your`. ;) and then merge if the instructions are correct..

**Comment by MarkusTeufelberger** [comment]
In general I'd like to see some spell checking going on before merging. ;-)

**Comment by cryptonit** [comment]
closed because of non proper spelling-
its just a help how i do prefer to explain to people and see it as most easy to understand im not going to spellcheck u can see it also in closed state if u seek inspiration

**Comment by d10r** [comment]
The input partly already went into https://github.com/lab10-coop/sigma1. I'll update tau1 readme too asap.

**Pull request closed without merging**
